### ISSUE TITLE
Bikin halaman buku

### ISSUE THREAD

**Issue by Rahmatuldani** [Rahmatuldani/dicoding-capstone#12]

**Comment by septiana25** [comment]
need review

**Comment by Rahmatuldani** [comment]
perlu perbaikan koneksi ke server serta atur hanya data buku saja yang disimpan ke state.books

**Comment by septiana25** [comment]
pengambilan data buku sudah diperbaiki

**Comment by septiana25** [comment]
update style 

1. hover: border, shadow
2. field search border

**Comment by septiana25** [comment]
add feature: pagination, search book
revision: rating, padding card book
